#!/usr/bin/env python3
"""Assemble REVISION_SUMMARY.md and revision_results.zip.

For each experiment, in the order §11 specifies:
  1. did it run as planned, and any deviations
  2. the headline_sentence
  3. the exact numbers that go into the manuscript
  4. **which existing manuscript sentences are now wrong** — which §11 says
     matters more than the new results, so it is generated by grepping the
     manuscript's own `%% >>> EXP-n` / `%% [PENDING]` markers rather than from
     memory, and is left explicit where an experiment has not run.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from scripts.revision.common_rev import REPO, REV, code_sha, utcnow  # noqa: E402

MANUSCRIPTS = REPO / "manuscripts"
EXPS = ["EXP-1", "EXP-2", "EXP-3", "EXP-4", "EXP-4b", "EXP-5", "EXP-5B",
        "EXP-5C", "EXP-6", "EXP-7", "EXP-8", "EXP-9"]

# A sub-experiment reports under its own row but lands on its parent's
# manuscript markers, and — where it replaces the planned experiment
# outright — is named in the parent's "did not run" block so the parent is
# never read as an unanswered question when it was answered another way.
PARENT = {"EXP-4b": "EXP-4", "EXP-5B": "EXP-5", "EXP-5C": "EXP-5"}
DELIVERED_BY = {"EXP-5": ["EXP-5B", "EXP-5C"]}

TITLES = {
    "EXP-1": "Rate versus absolute count",
    "EXP-2": "Threshold robustness",
    "EXP-3": "Dose-response model",
    "EXP-4": "SPECTRE and shortcut-suppressing augmentation",
    "EXP-4b": "Shortcut-suppressing augmentation",
    "EXP-5": "CheXpert transfer with true race labels",
    "EXP-5B": "Tercile-proxy validation (MIMIC)",
    "EXP-5C": "CheXpert Plus magnitude calibration",
    "EXP-6": "Audit detection-rate grid",
    "EXP-7": "Adversarial-debiasing lambda sweep",
    "EXP-8": "Clinical-harm translation",
    "EXP-9": "Figure regeneration for npj",
}

STATUS_OVERRIDE = {}   # filled from status.json if present


def _load(exp: str) -> dict | None:
    for name in ("summary.json", "spectre_summary.json", "finetune_summary.json"):
        f = REV / exp / name
        if f.exists():
            try:
                return json.loads(f.read_text())
            except json.JSONDecodeError:
                continue
    return None


def markers() -> dict[str, list[str]]:
    """Where each experiment's result lands, read from the manuscript itself."""
    out: dict[str, list[str]] = {e: [] for e in EXPS}
    for tex in sorted(MANUSCRIPTS.glob("*.tex")):
        for i, line in enumerate(tex.read_text().splitlines(), 1):
            m = re.search(r"EXP-(\d)([ab]?)", line)
            if m and line.lstrip().startswith("%%"):
                key = f"EXP-{m.group(1)}"
                if key in out:
                    out[key].append(f"{tex.name}:{i}  {line.strip()[:150]}")
    for sub, parent in PARENT.items():
        if not out.get(sub):
            out[sub] = list(out.get(parent, []))
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--zip", action="store_true", help="also build revision_results.zip")
    args = ap.parse_args()

    mk = markers()
    status_file = REV / "status.json"
    status = json.loads(status_file.read_text()) if status_file.exists() else {}

    lines = [
        "# REVISION_SUMMARY",
        "",
        f"Generated {utcnow()} · code `{code_sha()}`",
        "",
        "For each experiment: whether it ran as",
        "planned, its headline sentence, the numbers that go into the manuscript,",
        "and — the part §11 says matters most — **which existing manuscript",
        "sentences are now wrong**.",
        "",
        "> Running notes, including every deviation from the plan and the reason for",
        "> it, are in [`NOTES.md`](NOTES.md).",
        "",
        "---",
        "",
        "## Status at a glance",
        "",
        "| exp | title | status | headline available |",
        "|---|---|---|---|",
    ]
    docs = {}
    for e in EXPS:
        d = _load(e)
        docs[e] = d
        sub = [x for x in DELIVERED_BY.get(e, []) if _load(x)]
        st = status.get(e, "complete" if d
                        else (f"ran as {', '.join(sub)}" if sub else "not run"))
        lines.append(f"| {e} | {TITLES[e]} | {st} | {'yes' if d and d.get('headline_sentence') else 'no'} |")
    lines += ["", "---", ""]

    for e in EXPS:
        d = docs[e]
        sub = [x for x in DELIVERED_BY.get(e, []) if docs.get(x)]
        st = status.get(e, "complete" if d
                        else (f"ran as {', '.join(sub)}" if sub else "not run"))
        lines += [f"## {e} — {TITLES[e]}", "", f"**Status.** {st}", ""]

        if d is None:
            delivered = [x for x in DELIVERED_BY.get(e, []) if docs.get(x)]
            if delivered:
                lines += [
                    "**1. Did it run as planned?** Not as planned — it ran as "
                    + " and ".join(delivered)
                    + ". See those sections for the headline and the numbers; "
                    "the deviation and its reason are in NOTES.md.",
                    "",
                    "**2. Headline sentence.** _Reported under "
                    + ", ".join(delivered) + "._",
                    "",
                    "**3. Numbers for the manuscript.** _Reported under "
                    + ", ".join(delivered) + "._",
                    "",
                ]
            else:
                lines += [
                    "**1. Did it run as planned?** No — no summary artefact was produced.",
                    "",
                    "**2. Headline sentence.** _Not available._",
                    "",
                    "**3. Numbers for the manuscript.** _None._",
                    "",
                ]
        else:
            lines += [
                "**1. Did it run as planned?** "
                + (d.get("deviations") or "Yes; deviations, if any, are in NOTES.md."),
                "",
                "**2. Headline sentence.**",
                "",
                "> " + (d.get("headline_sentence") or "_not written_"),
                "",
                "**3. Numbers for the manuscript.**",
                "",
                "```json",
                json.dumps(_numbers(e, d), indent=2)[:6000],
                "```",
                "",
            ]

        lines += ["**4. Manuscript sentences that must change.**", ""]
        if mk[e]:
            lines.append("Insertion points carrying this experiment's result:")
            lines.append("")
            for loc in mk[e]:
                lines.append(f"- `{loc}`")
            lines.append("")
            if d is None and [x for x in DELIVERED_BY.get(e, []) if docs.get(x)]:
                sub = ", ".join(x for x in DELIVERED_BY[e] if docs.get(x))
                lines += [
                    f"> **{e} was delivered as {sub}.** The markers above are the "
                    f"insertion points; fill them from {sub} and state the "
                    f"substitution in the text — do not leave them `[PENDING]`.",
                    "",
                ]
            elif d is None:
                lines += [
                    f"> **{e} did not run.** Every marker above is still `[PENDING]`. "
                    f"Any sentence in the manuscript that presupposes this result "
                    f"must be softened or removed before submission, not left "
                    f"standing on an experiment that was not performed.",
                    "",
                ]
        else:
            lines += ["_No `%% >>> EXP-n` marker found in the manuscript for this "
                      "experiment._", ""]
        lines += ["---", ""]

    out = REV / "REVISION_SUMMARY.md"
    out.write_text("\n".join(lines))
    print(f"[summary] -> {out}")

    if args.zip:
        z = REV / "revision_results.zip"
        with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
            for p in [REV / "MANIFEST.json", REV / "NOTES.md", out]:
                if p.exists():
                    zf.write(p, p.name)
            for e in EXPS:
                seen = set()
                for pat in ("summary.json", "summary.csv", "NOTES.md", "*.json", "*.csv"):
                    for p in sorted((REV / e).glob(pat)):
                        if p.name in seen or p.stat().st_size >= 50_000_000:
                            continue
                        seen.add(p.name)
                        zf.write(p, f"{e}/{p.name}")
            for p in sorted((REPO / "results" / "figures").glob("fig*.png")):
                zf.write(p, f"figures/{p.name}")
            # the revision's own figures and the CSV written beside each one —
            # §11 asks for the regenerated figure set, not just the canonical nine
            for p in sorted((REV / "figures").glob("*")):
                if p.is_file() and p.stat().st_size < 50_000_000:
                    zf.write(p, f"figures/revision/{p.name}")
        print(f"[summary] -> {z}  ({z.stat().st_size/1e6:.1f} MB)")


def _numbers(exp: str, d: dict) -> dict:
    """The manuscript-facing subset of each summary, without the bulk."""
    drop = {"per_run", "per_seed", "history", "design", "per_cell",
            "bootstrap_ci_per_seed", "per_seed_fits", "calibration_table"}
    keep = {k: v for k, v in d.items() if k not in drop}
    if exp == "EXP-6":
        keep["detection_rates"] = {k: v for k, v in
                                   d.get("detection_rates", {}).items()
                                   if k in ("overall", "by_threshold", "by_cohort")}
    return keep


if __name__ == "__main__":
    main()
